"""initial database schema

Revision ID: 8eee3a6d3808
Revises: 
Create Date: 2025-11-19 14:57:29.028068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eee3a6d3808'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('international_name', sa.String(length=255), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=False, comment='Форма выпуска'),
    sa.Column('atc_code', sa.String(length=20), nullable=False, comment='АТХ код'),
    sa.Column('instruction', sa.Text(), nullable=False, comment='Инструкция по применению'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medicins_atc_code', 'medicins', ['atc_code'], unique=False)
    op.create_index(op.f('ix_medicins_id'), 'medicins', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False, comment='male, female, other'),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("sex IN ('male', 'female', 'other')", name='check_sex'),
    sa.CheckConstraint('age >= 0 AND age <= 150', name='check_age'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='appointment, prescription, test, reminder, alert'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Время отправки уведомления'),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_entity_id', sa.Integer(), nullable=True, comment='ID связанной сущности (appointment/prescription/test)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('appointment', 'prescription', 'test', 'reminder', 'alert')", name='check_notification_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='active, completed, cancelled, pending'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('share_with_doctor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled', 'pending')", name='check_plan_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plans_doctor_id', 'plans', ['doctor_id'], unique=False)
    op.create_index('idx_plans_user_id', 'plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_specialization', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='scheduled, completed, cancelled, missed'),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled', 'missed')", name='check_appointment_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointments_plan_id', 'appointments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('medical_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='active, completed, cancelled, expired'),
    sa.Column('repeat', sa.String(length=100), nullable=False, comment='Частота приёма'),
    sa.Column('medicin_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled', 'expired')", name='check_prescription_status'),
    sa.CheckConstraint('dosage > 0', name='check_dosage_positive'),
    sa.CheckConstraint('duration_days > 0', name='check_duration_positive'),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['medicin_id'], ['medicins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medical_prescriptions_medicin_id', 'medical_prescriptions', ['medicin_id'], unique=False)
    op.create_index('idx_medical_prescriptions_plan_id', 'medical_prescriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_medical_prescriptions_id'), 'medical_prescriptions', ['id'], unique=False)
    op.create_table('medical_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='scheduled, completed, cancelled, pending_results'),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled', 'pending_results')", name='check_test_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medical_tests_plan_id', 'medical_tests', ['plan_id'], unique=False)
    op.create_index(op.f('ix_medical_tests_id'), 'medical_tests', ['id'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symptoms_plan_id', 'symptoms', ['plan_id'], unique=False)
    op.create_index(op.f('ix_symptoms_id'), 'symptoms', ['id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False, comment='Оценка от 0 до 10'),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('value >= 0 AND value <= 10', name='check_survey_value_range'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_surveys_symptom_id', 'surveys', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.add_column('doctors', sa.Column('external_id', sa.String(length=100), nullable=False))
    op.add_column('doctors', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('doctors', sa.Column('specialization', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_doctors_external_id'), 'doctors', ['external_id'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.drop_column('doctors', 'name')
    op.drop_column('doctors', 'special')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('special', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_external_id'), table_name='doctors')
    op.drop_column('doctors', 'specialization')
    op.drop_column('doctors', 'full_name')
    op.drop_column('doctors', 'external_id')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.drop_index('idx_surveys_symptom_id', table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_symptoms_id'), table_name='symptoms')
    op.drop_index('idx_symptoms_plan_id', table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_medical_tests_id'), table_name='medical_tests')
    op.drop_index('idx_medical_tests_plan_id', table_name='medical_tests')
    op.drop_table('medical_tests')
    op.drop_index(op.f('ix_medical_prescriptions_id'), table_name='medical_prescriptions')
    op.drop_index('idx_medical_prescriptions_plan_id', table_name='medical_prescriptions')
    op.drop_index('idx_medical_prescriptions_medicin_id', table_name='medical_prescriptions')
    op.drop_table('medical_prescriptions')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index('idx_appointments_plan_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index('idx_plans_user_id', table_name='plans')
    op.drop_index('idx_plans_doctor_id', table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_medicins_id'), table_name='medicins')
    op.drop_index('idx_medicins_atc_code', table_name='medicins')
    op.drop_table('medicins')
    # ### end Alembic commands ###
