"""add_yandex_auth

Revision ID: de20c3889efd
Revises: 8eee3a6d3808
Create Date: 2025-11-24 10:55:26.253284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de20c3889efd'
down_revision: Union[str, None] = '8eee3a6d3808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_comment='male, female, other')
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_comment='male, female, other')
    op.drop_column('users', 'email')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
