"""add_original_file_path_to_plans

Revision ID: f3a4b2c1d5e6
Revises: de20c3889efd
Create Date: 2025-11-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a4b2c1d5e6'
down_revision: Union[str, None] = 'de20c3889efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('original_file_path', sa.String(length=500), nullable=True, comment='Путь к оригинальному PDF файлу'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'original_file_path')
    # ### end Alembic commands ###
